name: CustomWhitelist
version: 0.1-RELEASE
description: Allows modification to the whitelist even when Mojang UUID queries are rejected
author: Airship Pirates Programmers
main: org.minecraftairshippirates.customwhitelist.CustomWhitelistPlugin
database: false
commands:
    customwhitelist:
        description: Displays Custom Whitelist help
        usage: customwhitelist <add>
        aliases: cw
        
permissions:
    customwhitelist.*:
        description: Gives access to all CustomWhitelist commands
        children:
            customwhitelist.add: true
    customwhitelist.add:
        description: Allows you to add a player to the whitelist
        default: op
