name: CustomWhitelist
version: 0.5-SNAPSHOT
description: Allows modification to the whitelist even when Mojang UUID queries are rejected
author: Airship Pirates Programmers
main: org.minecraftairshippirates.customwhitelist.CustomWhitelistPlugin
database: false
commands:
    customwhitelist:
        description: Displays Custom Whitelist help
        usage: "Usage: /customwhitelist <add/remove/check/list/on/off>"
        aliases: cw
        
permissions:
    customwhitelist.*:
        description: Gives access to all CustomWhitelist commands
        children:
            customwhitelist.add: true
            customwhitelist.remove: true
            customwhitelist.check: true
            customwhitelist.list: true
            customwhitelist.on: true
            customwhitelist.off: true
    customwhitelist.add:
        description: Allows a player to be added to the whitelist
        default: op
    customwhitelist.remove:
        description: Allows a player to be removed from the whitelist
        default: op
    customwhitelist.check:
        description: Allows you to check if a player is on the whitelist
        default: op
    customwhitelist.list:
        description: Allows you to list all players on the whitelist
        default: op
    customwhitelist.on:
        description: Allows you to turn on the whitelist
        default: op
    customwhitelist.off:
        description: Allows you to turn off the whitelist
        default: op
